SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-daos3begekts73err76g-a/library-spring-db
SPRING_DATASOURCE_USERNAME=library_spring_db_user
SPRING_DATASOURCE_PASSWORD=H7NbP9V8mdAtbmztusg6iM22xOPAZTuy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000